name: Terraform Apply
on:
  push:
    branches:
      - 'main'
jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::482685573138:role/github-actions-oidc-example20230214125148478300000001
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
          terraform_wrapper: false
      - name: 'Deploy database'
        run: |
          cd integ/data-stores/mysql
          terraform init
          terraform apply -auto-approve
          cd -
permissions:
  id-token: write
